apiVersion: v1
kind: Service
metadata:
  name: apache-reverse-proxy
spec:
  selector:
    app: apache-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
