name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in GitHub secrets

      # Build and push blog-service image
      - name: Build and push blog-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-service:latest ./microservices/blog-service
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-service:latest

      # Build and push auth-service image
      - name: Build and push auth-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest ./microservices/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      # Build and push analytics-service image
      - name: Build and push analytics-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/analytics-service:latest ./microservices/analytics-service
          docker push ${{ secrets.DOCKER_USERNAME }}/analytics-service:latest

      # Build and push reverse-proxy image
      - name: Build and push reverse-proxy image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reverse-proxy:latest ./reverse-proxy
          docker push ${{ secrets.DOCKER_USERNAME }}/reverse-proxy:latest
